### ISSUE TITLE
Driver doesn't automatically download Chromedriver

### ISSUE THREAD

**Issue by laellsr** [appium/appium-chromium-driver#363]
Months ago this functionality was normal, but yesterday I installed the driver from scratch and it didn't automatically download the chromedriver.

```
[f8167839][ChromiumDriver@77e6] Session created with session id: f8167839-0638-420d-8e0b-18bf4b9c3ac5
[f8167839][Chromedriver@375e] Changed state to 'starting'
[f8167839][Chromedriver@375e] Error: Trying to use a chromedriver binary at the path C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe, but it doesn't exist!
    at Chromedriver.initChromedriverPath (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\appium-chromedriver\lib\chromedriver.js:504:13)
    at Chromedriver.start (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\appium-chromedriver\lib\chromedriver.js:624:32)
    at ChromiumDriver.startChromedriverSession (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\lib\driver.js:104:58)
    at ChromiumDriver.createSession (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\lib\driver.js:73:26)
    at AppiumDriver.createSession (C:\Users\lael_\AppData\Roaming\npm\node_modules\appium\lib\appium.js:739:35)
 Error: Trying to use a chromedriver binary at the path C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe, but it doesn't exist!
    at Chromedriver.initChromedriverPath (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\appium-chromedriver\lib\chromedriver.js:504:13)
    at Chromedriver.start (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\appium-chromedriver\lib\chromedriver.js:624:32)
    at ChromiumDriver.startChromedriverSession (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\lib\driver.js:104:58)
    at ChromiumDriver.createSession (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\lib\driver.js:73:26)
    at AppiumDriver.createSession (C:\Users\lael_\AppData\Roaming\npm\node_modules\appium\lib\appium.js:739:35)
[f8167839][Chromedriver@375e] [
  "Trying to use a chromedriver binary at the path C:\\Users\\lael_\\.appium\\node_modules\\appium-chromium-driver\\node_modules\\appium-chromedriver\\chromedriver\\win\\chromedriver.exe, but it doesn't exist!"
]
[f8167839][AppiumDriver@06a1] Event 'newSessionStarted' logged at 1729182842598 (13:34:02 GMT-0300 (Horário Padrão de Brasília))
[f8167839][AppiumDriver@06a1] Encountered internal error running command: Error: Trying to use a chromedriver binary at the path C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe, but it doesn't exist!
    at Object.errorWithException (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\@appium\support\lib\logging.js:41:45)
    at Object.errorAndThrow (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\@appium\support\lib\logging.js:44:18)
    at Chromedriver.start (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\node_modules\appium-chromedriver\lib\chromedriver.js:719:16)
    at ChromiumDriver.startChromedriverSession (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\lib\driver.js:104:58)
    at ChromiumDriver.createSession (C:\Users\lael_\.appium\node_modules\appium-chromium-driver\lib\driver.js:73:26)
    at AppiumDriver.createSession (C:\Users\lael_\AppData\Roaming\npm\node_modules\appium\lib\appium.js:739:35)
[f8167839][HTTP] <-- POST /session 500 18 ms - 978
```

- Appium v2.12.0
- chromium@1.3.54 
- Appium java client 7
- Java 8

**Comment by KazuCocoa** [comment]
Please run install command as https://github.com/appium/appium-chromium-driver?tab=readme-ov-file#install-chromedriver (`appium driver run chromium install-chromedriver`) to install the latest chromedriver which is the same behavior in `1.3.35` and lower.

**Comment by laellsr** [comment]
Thank you very much for help me!
I installed version `1.4.1` and it worked with the command `appium driver run chromium install-chromedriver`
